local config = {
    BINANCE_API_KEY = "YOUR_BINANCE_API_KEY",
    BINANCE_SECRET_KEY = "YOUR_BINANCE_SECRET_KEY",
    TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN",
    TELEGRAM_CHAT_ID = "YOUR_CHAT_ID",
    UPDATE_INTERVAL = 30,
    PRICE_CHANGE_THRESHOLD = 0.5,
    DATABASE_PATH = "crypto_tracker.db",
    RSI_PERIOD = 14,
    ENABLE_MARKET_ANALYSIS = true,
    ENABLE_DATABASE_LOGGING = true,
    MAX_RETRIES = 3,
    RETRY_DELAY = 5,
    ALERT_COOLDOWN = 300,
    LOG_LEVEL = "INFO",
    TEMP_DIR = "/tmp",
    CHART_STYLE = "lines",
    NOTIFICATION_COOLDOWN = 300,
    SHORT_MA_PERIOD = 7,
    MEDIUM_MA_PERIOD = 25,
    LONG_MA_PERIOD = 99,
    VOLUME_THRESHOLD = 1.5,
    ENABLE_CHARTS = true
}

return config 